// Auto-generated by CardCargo v88 apply.sh.
// Only top-level shipment tables and Shipment<->Package relation tables
// discovered from the local source are included.
export const shipmentTableCandidates = [
  "shipments",
  "international_shipments",
  "outbound_shipments"
] as const

export const shipmentPackageTableCandidates = [
  "shipment_warehouse_packages",
  "international_shipment_packages",
  "outbound_shipment_packages",
  "shipment_packages",
  "warehouse_package_shipments"
] as const
